version: '3.8'
services:
  userservicedb:
    container_name: userservicedb
    image: postgres:14.5-alpine
    ports:
      - '5433:5432' 
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      
  user-service:
    container_name: user-service
    build: ./user-service
    ports:
      - '8000:8000'
    depends_on:
      - userservicedb
    volumes:
    - ./user-service/src:/usr/src/user-service/src

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - user-service
    volumes:
    - ./frontend/src:/usr/src/frontend/src



volumes:
  pgdata: