export const STATUS_CODE_SUCCESS = 200
export const STATUS_CODE_CREATED = 201
export const STATUS_CODE_SUCCESSFULLY_UPDATED = 204

export const STATUS_BAD_REQUEST = 400

export const STATUS_UNAUTHORIZED = 401
export const STATUS_CODE_CONFLICT = 409
