version: '3.8'
services:
  userservicedb:
    container_name: userservicedb
    image: postgres:14.5-alpine
    ports:
      - '5433:5432' 
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      
  user-service:
    container_name: user-service
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - userservicedb
    volumes:
    - ./src:/usr/src/user-service/src
    # - ./dist:/usr/src/user-service/dist



volumes:
  pgdata: