apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: chat-service
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: chat-service
    spec:
      containers:
        - image: chat-service
          name: chat-service
          ports:
            - containerPort: 8003
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/chat-service/src
              name: chat-service-claim0
      restartPolicy: Always
      volumes:
        - name: chat-service-claim0
          persistentVolumeClaim:
            claimName: chat-service-claim0
status: {}
