apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: question-service
  name: question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: question-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: question-service
    spec:
      containers:
        - image: question-service
          name: question-service
          ports:
            - containerPort: 8002
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/question-service/src
              name: question-service-claim0
      restartPolicy: Always
      volumes:
        - name: question-service-claim0
          persistentVolumeClaim:
            claimName: question-service-claim0
status: {}
