apiVersion: v1
kind: Service
metadata:
  labels:
      app: userservicedb
  name: userservicedb
spec:
  selector:
    app: userservicedb
  ports:
    - name: http
      port: 5433
      targetPort: 5432
      protocol: TCP
      targetPort: http