version: '3.8'
services:
  questionservicedb:
    container_name: questionservicedb
    image: postgres:14.5-alpine
    ports:
      - '5434:5432' 
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      
  question-service:
    container_name: question-service
    build: .
    ports:
      - '8002:8002'
    depends_on:
      - questionservicedb
    volumes:
    - ./src:/usr/src/question-service/src

volumes:
  pgdata: